name: baskteer
description: Baskteer app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^3.2.3+1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
